### ISSUE TITLE
add `into_payload() -> IppPayload` for `IppRequestResponse`

### ISSUE THREAD

**Issue by ArcticLampyrid** [ancwrd1/ipp.rs#10]
Please add `into_payload() -> IppPayload` for `IppRequestResponse`.
Sometimes we need the ownership of `IppPayload`. It will be helpful to operate with something like `futures::io::BufReader` or `async-compression`.

**Comment by ArcticLampyrid** [comment]
`payload` field is public, so we can do this without `into_payload`.

**Comment by ancwrd1** [comment]
I guess I can add it but you can also write something like this:

```rust
let payload = std::mem::replace(response.payload_mut(), IppPayload::empty());
```
