### ISSUE TITLE
 device usage report

### ISSUE THREAD

**Issue by reneacosta** [ancwrd1/ipp.rs#11]
How can I access the printer usage report with this crate???

**Comment by ancwrd1** [comment]
Hi, for printer usage reports I think you need to use one of the SNMP crates and read vendor-specific MIB counters:
https://github.com/mds5000/rsnmp/
https://github.com/ancwrd1/rust-snmp
https://github.com/XAMPPRocky/rasn (only protocol codec, no transport)

Some generic MIB counters (such as number of printed pages) are supported by all vendors but most are vendor-specific, for example number of large, color and duplex pages, toner usage, etc.
