### ISSUE TITLE
Way to Print Images

### ISSUE THREAD

**Issue by Coops0** [ancwrd1/ipp.rs#17]
Was wondering if there was an easier way to print images that didn't require converting them to pdfs?

I'm sure it's printer specific, but I'm thinking maybe I'm missing some argument? I've tested and only .docx, .txt, and .pdf work. HEIC, PNG, or TIFF files all print the bytes over a ton of sheets of paper.

```rust
pub async fn print_ipp(args: PrintArgs) -> Result<()> {
    // todo fix this blocking call
    let payload = IppPayload::new(std::fs::File::open(args.file)?);

    let mut ip = args.ip.clone();
    if !ip.starts_with("http") {
        ip = format!("http://{ip}");
    }

    let uri: Uri = Uri::try_from(ip.clone())?;

    let mut builder = IppOperationBuilder::print_job(uri.clone(), payload)
        .user_name("noname")
        .job_title(ip);

    if args.copies != 1 {
        builder = builder.attribute(IppAttribute::new(
            "copies",
            IppValue::Integer(args.copies as i32),
        ));
    }

    let operation = builder.build();
    let client = AsyncIppClient::new(uri);

    let response = client.send(operation).await?;

    // ... rest of handling code

    Ok(())
}
```

**Comment by ancwrd1** [comment]
You could read target printer attributes and check "document-format-supported" list.
I think it's also possible to specify this attribute in the print request but the behavior is printer-specific.

**Comment by Coops0** [comment]
Great ideas. Will definitely try both of those and get back. Thank you! I'm messing with a ton of different HP printer types so I can't have one spewing out 70 pages of random garbage. 

Also- what's the way to use the print_async method? I can't find a library or structure that implements the AsyncRead trait.

**Comment by ancwrd1** [comment]
There is an example called `print-job-async`, but it doesn't use the async payload for some reason, I guess I just forgot to fix it.
You could use tokio for the async I/O like this:

```rust
use tokio_util::compat::TokioAsyncReadCompatExt;
use tokio::fs::File;

let payload = IppPayload::new_async(File::open(source).await?.compat());
```

**Comment by Coops0** [comment]
Wow I completely missed that compat stuff. Thank you!
