### ISSUE TITLE
Why are collections exposed as Vec?

### ISSUE THREAD

**Issue by ggodlewski** [ancwrd1/ipp.rs#18]
I'm trying to get printer attributes but they are exposed as Vec instead of HashMap.
In IPP "collection" is a list of key/value pairs that have been grouped together.

This is the code to print data that I need. Unfortunately it doesn't work recursively.

```
match attrib.value() {
    IppValue::Collection(col) => {
        let mut map: HashMap<&String, &IppValue> = HashMap::new();
        for idx in (0..col.len()).step_by(2) {
            match (col.get(idx), col.get(idx + 1)) {
                (Some(IppValue::MemberAttrName(k)), Some(v)) => {
                    map.insert(k, v);
                },
                _ => {}
            }
        }
        println!("{:?} {:#?}", attrib.name(), map);
    }
    _ => {
        println!("{:?} {:#?}", attrib.name(), attrib.value());
    }
}
```

I think the `IppValue::Collection` type should be changed.

**Comment by ancwrd1** [comment]
> In IPP "collection" is a list of key/value pairs that have been grouped together.

That's not entirely correct. Collection is a named group of values, not a list of key/value pairs. It is similar to arrays, the difference is each array's element has the same type and collections may have different types. See this for details: https://datatracker.ietf.org/doc/html/rfc8010#page-12

Your code assumes that the elements of the collection are key and value., but they are just values.

**Comment by ggodlewski** [comment]
https://datatracker.ietf.org/doc/html/rfc8010#section-3.1.7 says each member attribute contains pair of  0x4A MemberAttrName and member value.
More info on models is in [RFC8011](https://datatracker.ietf.org/doc/html/rfc8011)
Cups seems to implement it like it is hashmap.

It would be really useful if user can access fields like a hashmap. I created a PR.

**Comment by ancwrd1** [comment]
Ok, ok. Technically still a list of values though. I will check the PR, thanks.

**Comment by ggodlewski** [comment]
Thanks for the suuport. Just imagine this code using vectors:
```
if let Some(medias) = group.attributes().get("media-col-ready") {
    if let IppValue::Collection(map) = medias.value() {
        match (map.get("media-type"), map.get("media-size")) {
            (Some(IppValue::Keyword(media_type)), Some(IppValue::Collection(media_size))) => {
                println!("Type = {}", media_type);
                println!("Size = {}x{}", media_size.get("x-dimension").unwrap(), media_size.get("y-dimension").unwrap());
            }
            _ => {
                println!("Media col read = {:?}", medias);
            }
        }
    }
}
```
