### ISSUE TITLE
nameWithLanguage & textWithLanguage unhandled

### ISSUE THREAD

**Issue by Stroniax** [ancwrd1/ipp.rs#21]
The `nameWithLanguage` value tag is not handled properly. I believe this is somehow causing the response to not be read once a value of this type is received.

According to [RFC8010](https://datatracker.ietf.org/doc/html/rfc8010#page-23) `nameWithLanguage` is,
> OCTET-STRING consisting of four fields: a SIGNED-SHORT, which is the number of octets in the following field; a value of type natural-language; a SIGNED-SHORT, which is the number of octets in the following field; and a value of type nameWithoutLanguage.  The length of a nameWithLanguage value MUST be 4 + the value of field a + the value of field c.

From my understanding (based on a response I am looking at), this means that `nameWithLanguage` will take the following binary form:
``
0002 // length of natural-language
656E // natural-language: en
0004 // length of nameWithoutLanguage
54657374 // nameWithoutLanguage: "54657374"
``

This means that the naïve handling of `IppValue::Other` will not read the entire value, leading to a failure to read the response. However, the example response, when I tried to read it, does not fail with an error; I get an `IppRequestResponse` that does not contain all of the attributes of the job.

----

I suspect this also applies to `textWithoutLanguage` which is also not defined.

**Comment by ancwrd1** [comment]
Thanks for reporting this; those textWithLanguage and nameWithLanguage values are not implemented for some reason, I probably missed them. If you have perhaps a binary sample I can have a look how they are encoded.
I'd actually expect the `IppValue::Other` to be used as a fallback for unrecognized tags.

**Comment by Stroniax** [comment]
I believe because there is one `size` that indicates the size of the language, followed by a `size` indicating size of the value, I suspect the language itself is parsed as `other` and the first byte of the size of the `value` is read as a delimiter/value tag `00`. not sure where this leads however.

Here's a hex string representing the binary portion this value:
```
+ "36" // value tag - name-with-language
+ "0008" // name length: 8
+ "6A6F622D6E616D65" // name: job-name
+ "0002" // value length: 2
+ "656E" // value: en
+ "0004" // value length: 4
```
Here is the entire response which revealed to me that this attribute was unhandled:
```
"0101" // version
+ "0000" // status code
+ "00000001" // operation id
+ "01" // delimiter tag - operation attributes
+ "47" // value tag - charset
+ "0012" // name length
+ "617474726962757465732D63686172736574" // name: attributes-charset
+ "0005" // value length
+ "7574662D38" // value: utf-8
+ "48" // value tag - natural language
+ "001B" // name length: 27
+ "617474726962757465732D6E61747572616C2D6C616E6775616765" // name: attributes-natural-language
+ "0005" // value length
+ "656E2D7573" // value: en-us
+ "02" // delimiter tag - job attributes
+ "45" // value tag - job-uri
+ "0007" // name length
+ "6A6F622D757269" // name: job-uri
+ "0026" // value length: 38
+ "6970703A2F2F31302E3232382E3132392E38372F6970702F706F7274312F6A6F622D30303034" // value: ipp://10.228.129.87/ipp/port1/job-0004
+ "21" // value tag - job-id
+ "0006" // name length
+ "6A6F622D6964" // name: job-id
+ "0004" // value length
+ "00000004" // value
+ "45" // value tag - job-state
+ "000F" // name length: 15
+ "6A6F622D7072696E7465722D757269" // name: job-printer-uri
+ "001D" // value length: 29
+ "6970703A2F2F31302E3232382E3132392E38372F6970702F706F727431" // value: ipp://10.228.129.87/ipp/port1
+ "36" // value tag - name-with-language
+ "0008" // name length: 8
+ "6A6F622D6E616D65" // name: job-name
+ "0002" // value length: 2
+ "656E" // value: en
+ "0004" // value length: 4
+ "54657374" // Test
+ "36" // value tag - name-with-language
+ "0019" // name length: 25
+ "6A6F622D6F726967696E6174696E672D757365722D6E616D65" // name: job-originating-user-name
+ "0002" // value length: 2
+ "656E" // value: en
+ "0008" // value length: 8
+ "5465737455736572" // TestUser
+ "23" // value tag - enum
+ "0009" // name length: 9
+ "6A6F622D7374617465" // name: job-state
+ "0004" // value length: 4
+ "00000005" // value: 5 (Processing)
+ "44" // value tag - keyword
+ "0011" // name length: 17
+ "6A6F622D73746174652D726561736F6E73" // name: job-state-reasons
+ "0004" // value length: 4
+ "6E6F6E65" // value: none
+ "21" // value tag - integer
+ "0010" // name length: 16
+ "74696D652D61742D6372656174696F6E" // name: time-at-creation
+ "0004" // value length: 4
+ "00572C58" // value: 14600000
+ "21" // value tag - integer
+ "0012" // name length: 18
+ "74696D652D61742D70726F63657373696E67" // name: time-at-processing
+ "0004" // value length
+ "00572C58" // value: 14600000
+ "21" // value tag - integer
+ "0011" // name length: 17
+ "74696D652D61742D636F6D706C65746564" // name: time-at-completed
+ "0004" // value length: 4
+ "00000000" // value: 0
+ "21" // value tag - integer
+ "0013" // name length: 19
+ "6A6F622D7072696E7465722D75702D74696D65" // name: job-printer-up-time
+ "0004" // value length: 4
+ "0057351C" // value: 14600000
+ "21" // value tag - integer
+ "0019" // name length: 25
+ "6A6F622D696D7072657373696F6E732D636F6D706C65746564" // name: job-impressions-completed
+ "0004" // value length: 4
+ "00000000" // value: 0
+ "21" // value tag - integer
+ "001A" // name length: 26
+ "6A6F622D6D656469612D7368656574732D636F6D706C65746564" // name: job-media-sheets-completed
+ "0004" // value length: 4
+ "00000000" // value: 0
+ "47" // value tag - charset
+ "0012" // name length: 18
+ "617474726962757465732D63686172736574" // name: attributes-charset
+ "0005" // value length: 5
+ "7574662D38" // value: utf-8
+ "48" // value tag - natural language
+ "001B" // name length: 27
+ "617474726962757465732D6E61747572616C2D6C616E6775616765" // name: attributes-natural-language
+ "0002" // value length: 2
+ "656E" // value: en
+ "03" // delimiter tag - end of attributes
```

**Comment by ancwrd1** [comment]
That actually looks like an incorrect encoding in the response because the name-with-language/text-with-language does not have a value length which is mandatory.

I should be like this according to the specification (like all other attributes are constructed):

```text
"36" // value tag - name-with-language
"0008" // name length: 8
"6A6F622D6E616D65" // name: job-name
"000A" // value length
"0002" // length of natural-language: 2
"656E" // value of natural-language: en
"0004" // length of nameWithoutLanguage: 4
"54657374" // value of nameWithoutLanguage: test
```

**Comment by Stroniax** [comment]
Well that's unfortunate, I guess my printer is encoding the response incorrectly, but it does make handling that data a lot easier in the case of a properly functioning device.

**Comment by ancwrd1** [comment]
I have added the missing two value types anyway.
