### ISSUE TITLE
Support printing with `ipp://` scheme

### ISSUE THREAD

**Issue by beyerleinf** [ancwrd1/ipp.rs#23]
When trying to print using a URI with the `ipp://` scheme, I get the following error

```
kind: UnknownScheme, message: Some("unknown scheme 'ipp'")
```

It would be nice if the library could support URIs such as the following
```rs
let uri: Uri = "ipp://<printer ip>/ipp/print".parse()?;
let client = IppClient::new(uri.clone());
```

**Comment by ancwrd1** [comment]
Thanks for reporting this, fixed.
