### ISSUE TITLE
Add rustls support

### ISSUE THREAD

**Issue by TobiasDeBruijn** [ancwrd1/ipp.rs#33]
Hi,

Would it be possible to add a feature which enables `reqwest/rustls-tls`?
That way I can use TLS without needing OpenSSL.

Thanks

**Comment by ancwrd1** [comment]
Yes, I can add that, however please note that rustls is not compatible with many printers because they use the old, deprecated or obsolete ciphers and signature algorithms. I couldn't get it working for example with some HP printers.

**Comment by ancwrd1** [comment]
I have added two feature flags: `client-rustls` and `async-client-rustls`.

**Comment by TobiasDeBruijn** [comment]
> Yes, I can add that, however please note that rustls is not compatible with many printers because they use the old, deprecated or obsolete ciphers and signature algorithms. I couldn't get it working for example with some HP printers.

Interesting. Hopefully my printer is a little more modern, such that I don't need OpenSSL
